import {AWARD_FORMATIONS,AWARD_POSITIONS,awardSlots,awardLeagueKey,defaultAwardBoard,validateAwardBoard,awardBoardKey,awardPeriod,rankAwardCandidates,assignAwardCandidate} from './league-awards-model.js';
import {updatePageSettings} from './league-page-model.js';
import {downloadAwardImage} from './league-awards-export.js';
if(!document.querySelector('#league-award-styles')){const css=document.createElement('link');css.id='league-award-styles';css.rel='stylesheet';css.href='/league-awards.css';document.head.append(css);}
const escape=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');

// Only accepted, league-scoped appearances may be supplied by the future result pipeline.
export function renderAwardsWorkbench({host,draft,onSettings,records=[]}){
 const settings=draft.settings,content=settings.pageContent?.awards||{},saved=content.savedBoards||[];
 let board=validateAwardBoard(content.workbench||defaultAwardBoard(settings)),activeSlot=awardSlots(board.formation)[0].id,demo=false,selectedCandidate=null,dragId=null,dirty=false;
 host.innerHTML=`<div class="awards-intro"><h3>Team of the Week / Team of the Season</h3><p>Always an 11-player award team, including a goalkeeper. ${escape(settings.format)} match rules do not change this formation.</p><p>League: <strong>${escape(settings.league)}</strong> · Season: <strong>${escape(settings.season)}</strong></p></div><form class="awards-filters"><label>Award<select name="type"><option value="week">Team of the Week</option><option value="season">Team of the Season</option></select></label><label data-week-filter>Week starts<input type="date" name="weekDate" required></label><label>Formation<select name="formation">${Object.keys(AWARD_FORMATIONS).map(formation=>`<option>${formation}</option>`).join('')}</select></label><label>Minimum appearances<input type="number" name="minAppearances" min="1" max="100" required></label><button class="button button-primary">Apply filters / load selection</button><small>Weekly windows include 7 days in ${escape(settings.timeZone)}. Season mode includes the full selected league season. Changing the period or formation loads its saved selection or an empty board; save first to keep your work.</small></form><div class="awards-actions"><button type="button" data-save-award>Save selection on this device</button><button type="button" data-export-award>Download PNG</button><label class="workshop-checkbox"><input type="checkbox" data-sample-award>Preview with sample players</label></div><p role="status" aria-live="polite" data-award-status></p><div class="awards-layout"><section class="awards-pitch-panel"><h3 data-board-title></h3><p data-board-period></p><div class="awards-pitch" aria-label="11-player award formation"></div><p>Choose a slot, then drag an eligible player onto it. You can also use a player’s Select button and choose a slot — no dragging required. Selected players may be removed individually.</p></section><aside class="awards-sidebar"><section class="award-eligibility"><h3>Position eligibility</h3><label>Winning position<select data-active-slot></select></label><p>Choose which played positions qualify for this slot. Goalkeepers remain goalkeeper-only. Eligibility uses recorded positions, never guesses from broad “defender” or “midfielder” labels.</p><div class="eligibility-options"></div></section><section class="award-candidates"><h3>Highest-rated eligible players</h3><p data-candidate-context></p><label>Find a candidate<input type="search" data-candidate-search placeholder="Player name"></label><div class="award-candidate-list"></div></section></aside></div>`;
 const form=host.querySelector('form'),pitch=host.querySelector('.awards-pitch'),slotSelect=host.querySelector('[data-active-slot]'),status=host.querySelector('[data-award-status]'),list=host.querySelector('.award-candidate-list');
 form.elements.type.value=board.type;form.elements.weekDate.value=board.weekDate;form.elements.formation.value=board.formation;form.elements.minAppearances.value=board.minAppearances;
 const report=text=>status.textContent=text;
 const syncType=()=>{host.querySelector('[data-week-filter]').hidden=form.elements.type.value==='season';form.elements.weekDate.required=form.elements.type.value==='week';};syncType();form.elements.type.onchange=syncType;
 const sampleRecords=()=>AWARD_POSITIONS.flatMap((position,index)=>[0,1].flatMap(number=>[0,1].map(game=>({status:'accepted',leagueKey:awardLeagueKey(settings),season:settings.season,matchId:`sample-${game}`,timestamp:Date.parse(`${board.weekDate}T18:00:00Z`)+game*86400000,playerId:`sample-${position}-${number}`,name:`Sample ${position} ${number+1}`,teamId:`sample-team-${number}`,teamName:`Sample team ${number+1}`,position,rating:Math.min(9.9,7.2+(index%6)*.3+number*.1+game*.1),badgeUrl:'/assets/ufl-mark.png'}))));
 const candidateFor=slotId=>rankAwardCandidates(demo?sampleRecords():records,{leagueKey:awardLeagueKey(settings),season:settings.season,timeZone:settings.timeZone,board,slotId,excludeDisconnectRatings:settings.pageContent?.stats?.excludeDisconnectRatings??true});
 const image=(url,label,cls)=>url?`<img class="${cls}" src="${escape(url)}" alt="${escape(label)}" crossorigin="anonymous" loading="lazy">`:`<span class="${cls} award-placeholder" aria-label="${escape(label)}">${escape(label.slice(0,2).toUpperCase())}</span>`;
 function assign(slotId,id){try{const player=candidateFor(slotId).find(player=>player.id===id);if(!player)throw Error('This player does not qualify for that position and date range.');board=assignAwardCandidate(board,slotId,player);activeSlot=slotId;selectedCandidate=null;dirty=true;draw();report(`${player.name} selected for ${slotId}. Save the selection to keep it.`);}catch(error){report(error.message);}}
 function drawCandidates(){
  const query=host.querySelector('[data-candidate-search]').value.trim().toLowerCase(),candidates=candidateFor(activeSlot).filter(player=>player.name.toLowerCase().includes(query));
  host.querySelector('[data-candidate-context]').textContent=`${activeSlot} · average rating from qualifying-position appearances · minimum ${board.minAppearances} appearance(s). ${demo?'SAMPLE DATA — not league results.':records.length?'Accepted league appearances only.':'Accepted league rating/position feed is not connected yet. No real candidates are available.'}`;
  list.innerHTML=candidates.map(player=>{const used=Object.values(board.selections).some(selected=>selected.id===player.id);return `<article class="award-candidate" draggable="${!used}" data-candidate="${escape(player.id)}">${image(player.portraitUrl,player.name,'candidate-face')}<div><strong>${escape(player.name)}</strong><small>${escape(player.teamName)} · ${escape(player.positions.join('/'))}</small><span>${player.averageRating.toFixed(2)} rating · ${player.appearances} apps</span></div><button type="button" ${used?'disabled':''}>${used?'Selected':'Select'}</button></article>`;}).join('')||'<p class="award-empty">No eligible candidates. Adjust the position/date/appearance filters. Missing exact positions or valid ratings are never guessed.</p>';
  list.querySelectorAll('[data-candidate]').forEach(row=>{row.ondragstart=event=>{dragId=row.dataset.candidate;event.dataTransfer.setData('text/plain',dragId);event.dataTransfer.effectAllowed='copy';};row.ondragend=()=>dragId=null;row.querySelector('button').onclick=()=>{selectedCandidate=row.dataset.candidate;report('Choose a formation slot to place this player.');};});
  list.querySelectorAll('img').forEach(img=>img.onerror=()=>{const placeholder=document.createElement('span');placeholder.className=img.className+' award-placeholder';placeholder.textContent=(img.alt||'?').slice(0,2).toUpperCase();img.replaceWith(placeholder);});
 }
 function draw(){
  const slots=awardSlots(board.formation),period=awardPeriod(board);if(!slots.some(slot=>slot.id===activeSlot))activeSlot=slots[0].id;
  host.querySelector('[data-board-title]').textContent=`${demo?'SAMPLE · ':''}${board.type==='week'?'Team of the Week':'Team of the Season'} · ${board.formation}`;
  host.querySelector('[data-board-period]').textContent=board.type==='week'?`${period.from} – ${period.to} · ${settings.timeZone}`:`Full season · ${settings.season}`;
  host.querySelector('[data-save-award]').disabled=demo;
  pitch.innerHTML=slots.map(slot=>{const player=board.selections[slot.id];return `<div class="award-slot ${activeSlot===slot.id?'is-active':''}" style="left:${slot.x}%;top:${slot.y}%;width:${slot.width}%" data-slot="${slot.id}"><button type="button" aria-label="${slot.id}${player?`, ${escape(player.name)}`:', empty'}" aria-pressed="${activeSlot===slot.id}">${player?image(player.portraitUrl,player.name,'award-player-face'):'<span class="slot-plus">+</span>'}<strong>${player?escape(player.name):slot.position}</strong>${player?`<span>${image(player.badgeUrl,player.teamName,'award-team-badge')}${player.averageRating.toFixed(2)}</span>`:`<small>${slot.id}</small>`}</button>${player?`<button type="button" class="remove-award-player" aria-label="Remove ${escape(player.name)} from ${slot.id}">×</button>`:''}</div>`;}).join('');
  pitch.querySelectorAll('[data-slot]').forEach(slot=>{
   slot.querySelector('button').onclick=()=>{if(selectedCandidate)assign(slot.dataset.slot,selectedCandidate);else{activeSlot=slot.dataset.slot;draw();}};
   slot.ondragover=event=>{event.preventDefault();event.dataTransfer.dropEffect='copy';};slot.ondrop=event=>{event.preventDefault();if(dragId)assign(slot.dataset.slot,dragId);};
   const remove=slot.querySelector('.remove-award-player');if(remove)remove.onclick=()=>{delete board.selections[slot.dataset.slot];dirty=true;draw();report('Player removed from this award selection. Save to keep the change.');};
  });
  slotSelect.innerHTML=slots.map(slot=>`<option value="${slot.id}" ${slot.id===activeSlot?'selected':''}>${slot.id}</option>`).join('');
  const slot=slots.find(slot=>slot.id===activeSlot),allowed=board.eligibility[activeSlot],options=host.querySelector('.eligibility-options');
  options.innerHTML=AWARD_POSITIONS.map(position=>`<label><input type="checkbox" value="${position}" ${allowed.includes(position)?'checked':''} ${(slot.position==='GK')!==(position==='GK')?'disabled':''}>${position}</label>`).join('');
  options.querySelectorAll('input').forEach(input=>input.onchange=()=>{const next=[...options.querySelectorAll('input:checked')].map(input=>input.value);if(!next.length){input.checked=true;report('Keep at least one qualifying position.');return;}board.eligibility[activeSlot]=next;const selected=board.selections[activeSlot];if(selected&&!candidateFor(activeSlot).some(player=>player.id===selected.id)){delete board.selections[activeSlot];report('Selection removed because it no longer qualifies.');}dirty=true;draw();});
  host.querySelectorAll('img').forEach(img=>img.onerror=()=>{const placeholder=document.createElement('span');placeholder.className=img.className+' award-placeholder';placeholder.textContent=(img.alt||'?').slice(0,2).toUpperCase();img.replaceWith(placeholder);});
  drawCandidates();
 }
 slotSelect.onchange=()=>{activeSlot=slotSelect.value;draw();};host.querySelector('[data-candidate-search]').oninput=drawCandidates;
 form.onsubmit=event=>{event.preventDefault();try{
  const values=Object.fromEntries(new FormData(form)),periodChanged=values.type!==board.type||values.weekDate!==board.weekDate,formationChanged=values.formation!==board.formation;
  const match=saved.find(entry=>awardBoardKey(entry)===`${values.type}:${values.type==='week'?values.weekDate:'season'}`);
  const restoring=periodChanged&&match&&!demo;
  const fresh=restoring?structuredClone(match):periodChanged||formationChanged?defaultAwardBoard(settings):structuredClone(board);
  if(restoring){values.formation=match.formation;values.minAppearances=match.minAppearances;form.elements.formation.value=match.formation;form.elements.minAppearances.value=match.minAppearances;}
  if(fresh.formation!==values.formation){fresh.formation=values.formation;fresh.eligibility={};fresh.selections={};}
  fresh.selections=Object.fromEntries(Object.entries(fresh.selections).filter(([,player])=>player.appearances>=Number(values.minAppearances)));
  board=validateAwardBoard({...fresh,type:values.type,weekDate:values.weekDate,minAppearances:Number(values.minAppearances)});
  // Without a connected appearance feed, retain saved snapshots rather than silently erasing them.
  if(demo||records.length)for(const [slotId,player] of Object.entries(board.selections))if(!candidateFor(slotId).some(candidate=>candidate.id===player.id))delete board.selections[slotId];
  activeSlot=awardSlots(board.formation)[0].id;selectedCandidate=null;dirty=true;draw();report('Filters applied. Ratings are ranked highest first; selection is not saved yet.');
 }catch(error){report(error.message);}};
 host.querySelector('[data-sample-award]').onchange=event=>{demo=event.target.checked;board.selections={};selectedCandidate=null;dirty=true;draw();report(demo?'SAMPLE MODE: fabricated players for testing the controls. Sample selections cannot be saved as league awards; exported images are watermarked.':'Sample mode off. Load a saved selection using Apply filters.');};
 host.querySelector('[data-save-award]').onclick=()=>{try{if(demo)throw Error('Sample awards cannot be saved.');const checked=validateAwardBoard(board),key=awardBoardKey(checked),boards=[...saved.filter(entry=>awardBoardKey(entry)!==key),checked];onSettings(updatePageSettings(settings,'awards',{...content,workbench:checked,savedBoards:boards}));dirty=false;}catch(error){report(error.message);}};
 host.querySelector('[data-export-award]').onclick=async event=>{const button=event.currentTarget;button.disabled=true;try{const count=Object.keys(board.selections).length;if(!count)throw Error('Select players before downloading an image.');const missing=await downloadAwardImage({settings,board,demo});report(`PNG downloaded${count<11?' — incomplete lineup labelled DRAFT':''}.${missing?' Some artwork could not load; initials/placeholders were used.':''}`);}catch(error){report(error.message);}finally{button.disabled=false;}};
 draw();
 return {hasUnsavedChanges:()=>dirty};
}
