const token=location.hash.slice(1),host=document.querySelector('#join-content'),status=document.querySelector('#join-status');
const escape=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
async function api(body){const response=await fetch('/api/registration',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(data.error);return data;}
async function load(){try{
 const response=await fetch('/api/registration?token='+encodeURIComponent(token)),data=await response.json();if(!response.ok)throw Error(data.error);
 host.innerHTML=`<span class="section-kicker">${escape(data.settings.season)} · ${escape(data.settings.format)}</span><h2>${escape(data.settings.league)}</h2><p>${data.kind==='player'?`Join ${escape(data.team.name)}`:'Register your team'} · roster maximum ${data.settings.maxTeamSize}</p>`;
 if(!data.user){host.insertAdjacentHTML('beforeend','<p>Sign in with Discord, then return to this invitation to continue.</p><a href="/api/auth/discord" target="_blank" rel="noopener">Sign in with Discord ↗</a><button type="button" data-refresh>I’m signed in — continue</button>');host.querySelector('button').onclick=load;return;}
 host.insertAdjacentHTML('beforeend',`<p>Signed in as ${escape(data.user.name)}</p>`);
 if(data.kind==='manager'&&data.team){host.insertAdjacentHTML('beforeend',`<h3>${escape(data.team.name)}</h3><p>${data.team.status==='approved'?'Team approved. Create a player invitation to share with your squad.':'Your team request is waiting for league administrator approval.'}</p>${data.team.status==='approved'?'<button type="button" data-player-link>Create / replace player invitation</button><p data-link></p>':''}`);if(data.team.status==='approved')host.querySelector('button').onclick=async()=>{try{const result=await api({action:'playerLink',teamId:data.team.id});const a=document.createElement('a');a.href=result.url;a.textContent=result.url;host.querySelector('[data-link]').replaceChildren(a);status.textContent='Share this link with your players. Older player links for this team are replaced.';}catch(e){status.textContent=e.message;}};return;}
 if(data.kind==='manager'&&!data.open){host.insertAdjacentHTML('beforeend','<p>Team registration is closed.</p>');return;}
 const form=document.createElement('form');form.innerHTML=data.kind==='manager'?'<label>Team name<input name="name" maxlength="80" required></label><label>EA club ID (optional)<input name="eaClubId" pattern="[0-9]{1,20}" inputmode="numeric"></label><button>Submit team for approval</button>':'<label>Your EA player name<input name="eaName" maxlength="80" required></label><p>Your Discord identity and EA name will be visible to league staff for roster review. This does not verify EA ownership.</p><button>Request to join this team</button>';host.append(form);
 form.onsubmit=async event=>{event.preventDefault();form.querySelector('button').disabled=true;try{await api({action:data.kind==='manager'?'team':'player',token,...Object.fromEntries(new FormData(form))});status.textContent='Submitted. League staff can now review your registration.';if(data.kind==='manager')await load();else form.remove();}catch(e){status.textContent=e.message;form.querySelector('button').disabled=false;}};
 }catch(e){host.textContent=e.message;}}
load();
