import {installWorkshopBrand} from './league-workshop-brand.js';
import {invitationCard,registrationSummary,statusBadge,watchUnsaved} from './league-workspace-status.js';
installWorkshopBrand();
const token=location.hash.slice(1),host=document.querySelector('#join-content'),status=document.querySelector('#join-status');
const escape=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
async function api(body){const response=await fetch('/api/registration',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw Error(data.error);return data;}
function gamingFields(profile){return `<fieldset class="editor-group"><legend>Your gaming identity</legend><p>Public ID only — never a password. Saved to your preview identity across leagues. EA verification will be added later.</p><div class="workshop-pair"><label>Gaming platform<select name="platform" required><option value="">Choose platform</option>${[['psn','PlayStation / PSN'],['ea','EA / Origin'],['xbox','Xbox']].map(([id,name])=>`<option value="${id}" ${profile?.platform===id?'selected':''}>${name}</option>`).join('')}</select></label><label>Public gaming ID<input name="accountName" value="${escape(profile?.accountName||'')}" maxlength="80" autocomplete="off" required></label></div></fieldset>`;}
function teamFields(team){return `<fieldset class="editor-group"><legend>Team details</legend><div class="workshop-pair"><label>Displayed team name<input name="name" value="${escape(team?.name||'')}" maxlength="80" required></label><label>In-game team name<input name="inGameName" value="${escape(team?.inGameName||'')}" maxlength="80" required></label></div><p>Use the exact club name in EA Clubs. Automatic search and a Recheck control will come later; this name is not verified yet.</p></fieldset>`;}
function submitForm(form,action){const mark=watchUnsaved(form,action==='updateTeam'?'Saved online':'Not submitted yet');form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;try{await api({action,token,...Object.fromEntries(new FormData(form))});await load();status.textContent=action==='updateTeam'?'Saved online · team details and gaming ID.':'Saved online · Pending approval.';}catch(e){mark('Unsaved changes');status.textContent=e.message;}finally{button.disabled=false;}};}
async function load(){try{
 const response=await fetch('/api/registration?token='+encodeURIComponent(token)),data=await response.json();if(!response.ok)throw Error(data.error);
 host.innerHTML=`<span class="section-kicker">${escape(data.settings.season)} · ${escape(data.settings.format)}</span><h2>${escape(data.settings.league)}</h2><p>${data.kind==='player'?`Join ${escape(data.team.name)}`:'Team registration'} · roster maximum ${data.settings.maxTeamSize}</p>`;
 if(!data.user){host.insertAdjacentHTML('beforeend','<p>Sign in with Discord, then return here to continue. Your league manager permissions are assigned by an owner/admin.</p><a href="/api/auth/discord" target="_blank" rel="noopener">Sign in with Discord</a><button type="button" data-refresh>I’m signed in — continue</button>');host.querySelector('button').onclick=load;return;}
 host.insertAdjacentHTML('beforeend',`<p>Signed in as ${escape(data.user.name)}</p>`);
 host.insertAdjacentHTML('beforeend',`<p class="league-important">${escape(registrationSummary(data.settings,data.registrationOpen))}</p>`);
 if(data.kind==='player'&&data.playerRequest){host.insertAdjacentHTML('beforeend',`<p>${data.playerRequest.status==='approved'?'You have an approved roster membership in this league.':'Your player request is awaiting league staff approval.'}</p><p>Only one team per league is allowed. You can register separately for another league in this season.</p>`);return;}
 if(data.kind==='manager'&&data.team){
  host.insertAdjacentHTML('beforeend',`${statusBadge(data.team.status)}<h3>${escape(data.team.name)}</h3><p>${data.team.status==='approved'?'Team approved. Share a player invitation with your squad.':'Awaiting league administrator approval.'}</p>`);
  if(!data.team.isManager){host.insertAdjacentHTML('beforeend','<p>Your manager access is disabled. Contact league staff.</p>');return;}
  const form=document.createElement('form');form.innerHTML=teamFields(data.team)+gamingFields(data.profile)+'<button class="button-primary" type="submit">Save team details</button>';host.append(form);submitForm(form,'updateTeam');
  if(data.team.status==='approved'){
   const controls=document.createElement('section');controls.className='rule-card';controls.innerHTML='<h3>Player invitations</h3><button type="button">Create / replace player invitation</button><p data-link></p>';host.append(controls);
   controls.querySelector('button').onclick=async event=>{event.target.disabled=true;try{const result=await api({action:'playerLink',teamId:data.team.id});invitationCard(controls.querySelector('[data-link]'),result.url,{...data.settings,kind:'Player',teamName:data.team.name});status.textContent='Saved online · player invitation. Any previous player link has been replaced.';}catch(e){status.textContent=e.message;}finally{event.target.disabled=false;}};
   const roster=document.createElement('section');roster.className='rule-card';roster.innerHTML=`<h3>Approved roster · ${data.roster.length}</h3><p>Managers do not occupy a playing slot automatically. Use the player invitation yourself if you also play.</p>${data.roster.map(p=>`<p><strong>${escape(p.display_name)}</strong> · ${escape(p.platform||'Legacy ID')} ${escape(p.account_name||'Gaming identity needs updating')}</p>`).join('')||'<p>No approved players yet. Staff review player requests in Teams.</p>'}`;host.append(roster);
  }return;
 }
 if(data.kind==='manager'&&!data.managerAccess){host.insertAdjacentHTML('beforeend','<p>A league owner/admin must select you as a Team Manager before you can register a team.</p><button type="button">Refresh manager access</button>');host.querySelector('button').onclick=load;return;}
 if(data.kind==='manager'&&!data.open){host.insertAdjacentHTML('beforeend','<p>Team registration is closed.</p>');return;}
 const form=document.createElement('form');form.innerHTML=(data.kind==='manager'?teamFields(null)+'<label>EA club ID (optional, unverified)<input name="eaClubId" pattern="[0-9]{1,20}" inputmode="numeric"></label>':'<p>You may play in multiple leagues, but only for one team within each league. Your Discord identity and public gaming ID are visible to league staff and your team manager.</p>')+gamingFields(data.profile)+`<button class="button-primary" type="submit">${data.kind==='manager'?'Submit team for approval':'Request to join this team'}</button>`;host.append(form);submitForm(form,data.kind==='manager'?'team':'player');
 }catch(e){host.textContent=e.message;}}
load();
