import {awardSlots,awardPeriod} from './league-awards-model.js';
import {downloadAwardImage} from './league-awards-export.js';
const escape=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const season=document.querySelector('#award-season'),tabs=document.querySelector('#award-weeks'),host=document.querySelector('#award-publications'),status=document.querySelector('#archive-status');
let publications=[],active=null;
function image(url,label,cls){return url?`<img class="${cls}" src="${escape(url)}" alt="${escape(label)}" crossorigin="anonymous" loading="lazy">`:`<span class="${cls} award-placeholder">${escape(label.slice(0,2).toUpperCase())}</span>`;}
function draw(){
 if(!publications.length){tabs.innerHTML='';host.innerHTML='';status.textContent='No awards published yet. Owner/admin selections will appear here after publication.';return;}
 const entries=publications.filter(entry=>entry.settings.season===season.value),weeks=[...new Set(entries.filter(e=>e.board.type==='week').map(e=>e.weekNumber))].sort((a,b)=>a-b),keys=[...weeks.map(String),...(entries.some(e=>e.board.type==='season')?['season']:[])];
 if(!keys.includes(active))active=keys.at(-1);
 tabs.innerHTML=keys.map(key=>`<button role="tab" aria-selected="${key===active}" tabindex="${key===active?0:-1}" data-week="${key}">${key==='season'?'Team of the Season':`Week ${key}`}</button>`).join('');
 tabs.querySelectorAll('button').forEach(button=>{button.onclick=()=>{active=button.dataset.week;draw();tabs.querySelector('[aria-selected="true"]').focus();};button.onkeydown=event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const index=keys.indexOf(active);active=event.key==='Home'?keys[0]:event.key==='End'?keys.at(-1):keys[(index+(event.key==='ArrowRight'?1:-1)+keys.length)%keys.length];draw();tabs.querySelector('[aria-selected="true"]').focus();};});
 const selected=entries.filter(e=>active==='season'?e.board.type==='season':e.board.type==='week'&&e.weekNumber===Number(active));
 host.innerHTML=['6v6','10v10'].map(format=>{const group=selected.filter(e=>e.settings.format===format);return group.length?group.map(entry=>{const {board,settings}=entry,period=awardPeriod(board),title=`${active==='season'?'Season':`Week ${active}`} · ${format} ${active==='season'?'TOTS':'TOTW'}`;return `<article class="published-award"><h2>${title}</h2><p><strong>${escape(settings.league)}</strong> · ${escape(settings.season)}</p><p>${board.type==='week'?`${period.from} – ${period.to}`:'Full season'} · ${escape(settings.timeZone)}</p><div class="awards-pitch" aria-label="${title} formation">${awardSlots(board.formation).map(slot=>{const player=board.selections[slot.id],ai=slot.position==='GK'?board.aiKeeper:null;if(!player&&!ai)return '';return `<div class="award-slot" style="left:${slot.x}%;top:${slot.y}%;width:${slot.width}%">${player?image(player.portraitUrl,player.name,'award-player-face'):'<span class="slot-plus">AI</span>'}<strong>${escape(player?.name||ai.name)}</strong><small>${slot.position} · ${player?player.averageRating.toFixed(2):'AI keeper'}</small>${player?image(player.badgeUrl,player.teamName,'award-team-badge'):'<small>Not a player award</small>'}</div>`;}).join('')}</div><p>${escape(board.formation)} · ${board.selections['GK-1']?'Player keeper selected':board.aiKeeper?'AI keeper shown for presentation only':'Goalkeeper left blank'}</p><button type="button" data-download="${entry.id}">Download PNG</button><p>Revision ${entry.revision} · Published ${escape(entry.publishedAt)} UTC</p></article>`;}).join(''):`<article class="published-award"><h2>${format} ${active==='season'?'TOTS':'TOTW'}</h2><p>No selection published for ${active==='season'?'this season':`week ${active}`} yet.</p></article>`;}).join('');
 host.querySelectorAll('[data-download]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{const entry=selected.find(e=>e.id===button.dataset.download);await downloadAwardImage(entry);status.textContent='PNG downloaded.';}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
 host.querySelectorAll('img').forEach(img=>img.onerror=()=>{const span=document.createElement('span');span.className=img.className+' award-placeholder';span.textContent=(img.alt||'?').slice(0,2).toUpperCase();img.replaceWith(span);});
 status.textContent=publications.length?'':'No awards published yet. Owner/admin selections will appear here after publication.';
}
season.onchange=()=>{active=null;draw();};
try{const response=await fetch('/api/awards'),data=await response.json();if(!response.ok)throw Error(data.error);publications=data.publications;const seasons=[...new Set(publications.map(e=>e.settings.season))];season.innerHTML=seasons.map(s=>`<option>${escape(s)}</option>`).join('');season.disabled=!seasons.length;draw();}catch(error){status.textContent=error.message||'Published selections could not load. Please try again.';}
