import assert from 'node:assert/strict';
import {defaultAwardBoard,awardSlots,validateAwardBoard} from '../league-awards-model.js';
import {awardComplete,validatePublication,officialAwardPlayers,publicationIdentity} from '../league-awards-publication.js';
import {previewAwardsApi} from '../functions/_lib/preview-awards.js';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
const settings={league:'6v6 Test',season:'Season 2',format:'6v6',timeZone:'America/Chicago',startDate:'2026-10-08'};
const board=defaultAwardBoard(settings);
for(const slot of awardSlots(board.formation).filter(s=>s.position!=='GK'))board.selections[slot.id]={id:`p-${slot.id}`,name:`Player ${slot.id}`,teamId:'roma',teamName:'Roma',positions:[slot.position],averageRating:8,appearances:2};
assert.ok(awardComplete(board));
const payload={settings,board,weekNumber:1};
assert.equal(Object.keys(validatePublication(payload).board.selections).length,10);
board.aiKeeper={name:'AI keeper name'};
assert.equal(validatePublication(payload).board.aiKeeper.name,'AI keeper name');
assert.equal(officialAwardPlayers(board).length,10);assert.ok(!officialAwardPlayers(board).some(p=>p.name==='AI keeper name'));
assert.throws(()=>validatePublication({...payload,demo:true}));
assert.throws(()=>validatePublication({...payload,weekNumber:0}));
assert.throws(()=>validatePublication({...payload,board:{...board,selections:{}}}));
assert.throws(()=>validateAwardBoard({...board,aiKeeper:{name:''}}));
assert.throws(()=>validatePublication({...payload,board:{...board,selections:{...board.selections,'ST-1':{...board.selections['ST-1'],id:'sample-ST'}}}}));
assert.notEqual(publicationIdentity(validatePublication(payload)),publicationIdentity(validatePublication({...payload,settings:{...settings,format:'10v10',league:'10v10 Test'}})));
assert.notEqual(publicationIdentity(validatePublication(payload)),publicationIdentity(validatePublication({...payload,weekNumber:2})));
const origin='https://ufl-major-update-preview.pages.dev';
let actor=null,changed=1,writes=0;
const DB={prepare(sql){return {bind(){return this;},first:async()=>actor,all:async()=>({results:[]})};},batch:async()=>{writes++;return [{meta:{changes:changed}},{meta:{changes:0}},{meta:{changes:1}}];}};
const env={DB,OWNER_DISCORD_ID:'owner'};
const req=(headers={},body=payload)=>new Request(origin+'/api/awards',{method:'POST',headers:{origin,cookie:'__Host-ufl_session=test',...headers},body:JSON.stringify(body)});
assert.equal((await previewAwardsApi(req({origin:'https://evil.test'}),env)).status,403);
assert.equal((await previewAwardsApi(req(),env)).status,401);
actor={discord_id:'mod',role:'moderator',status:'active'};assert.equal((await previewAwardsApi(req(),env)).status,403);assert.equal(writes,0);
actor={discord_id:'admin',role:'admin',status:'active'};
assert.equal((await previewAwardsApi(req({}, {...payload,demo:true}),env)).status,400);
assert.equal((await previewAwardsApi(req(),env)).status,200);assert.equal(writes,1);
changed=0;assert.equal((await previewAwardsApi(req(),env)).status,409);
actor={discord_id:'owner',role:'member',status:'active'};changed=1;assert.equal((await previewAwardsApi(req(),env)).status,200);
assert.deepEqual(await (await previewAwardsApi(new Request(origin+'/api/awards'),env)).json(),{publications:[]});
const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../migrations/0016_preview_awards.sql',import.meta.url),'utf8'));
const realDB={prepare(sql){let params=[];return {bind(...args){params=args;return this;},first:async()=>actor,all:async()=>({results:sqlite.prepare(sql).all(...params)}),run(){const result=sqlite.prepare(sql).run(...params);return {meta:{changes:Number(result.changes)}};}};},async batch(statements){sqlite.exec('BEGIN');try{const results=statements.map(s=>s.run());sqlite.exec('COMMIT');return results;}catch(error){sqlite.exec('ROLLBACK');throw error;}}};
const actualEnv={...env,DB:realDB};
assert.equal((await previewAwardsApi(req(),actualEnv)).status,200);
assert.equal((await previewAwardsApi(req(),actualEnv)).status,409);
const edited={...payload,revision:1,board:{...board,aiKeeper:null}};
assert.equal((await previewAwardsApi(req({},edited),actualEnv)).status,200);
assert.equal((await previewAwardsApi(req({},edited),actualEnv)).status,409);
assert.equal(sqlite.prepare('SELECT count(*) AS n FROM preview_award_revisions').get().n,2);
const shared=await (await previewAwardsApi(new Request(origin+'/api/awards'),actualEnv)).json();assert.equal(shared.publications.length,1);assert.equal(shared.publications[0].revision,2);assert.equal(shared.publications[0].board.aiKeeper,null);
assert.equal(JSON.parse(sqlite.prepare('SELECT snapshot FROM preview_award_revisions WHERE revision=1').get().snapshot).board.aiKeeper.name,'AI keeper name');sqlite.close();
console.log('PASS: optional AI/blank GK, ten outfield publication, sample rejection, league/week identity, admin/owner authorization, CSRF and revision conflicts.');
