import assert from 'node:assert/strict';
import {LEAGUE_TABS,updatePageSettings,setPagePublished,editDraftTeam} from '../league-page-model.js';
const settings={league:'Empty league',teams:[]};
assert.equal(LEAGUE_TABS.length,10);
assert.equal(setPagePublished(settings,true).pagePublished,true);
assert.equal(setPagePublished(settings,true).teams.length,0);
assert.equal(setPagePublished(setPagePublished(settings,true),false).pagePublished,false);
let updated=updatePageSettings(settings,'rules',{text:'No amps.'});
updated=updatePageSettings(updated,'standings',{text:'Fair play',win:3,draw:1,loss:0});
assert.equal(updated.pageContent.rules.text,'No amps.');assert.equal(updated.pageContent.standings.win,3);
assert.equal(settings.pageContent,undefined);
assert.throws(()=>updatePageSettings(settings,'unknown',{}));
assert.throws(()=>updatePageSettings(settings,'rules',{text:'a'.repeat(10001)}));
assert.throws(()=>updatePageSettings(settings,'standings',{win:-1,draw:1,loss:0}));
assert.throws(()=>updatePageSettings(settings,'videos',{links:'javascript:alert(1)'}));
assert.throws(()=>updatePageSettings(settings,'videos',{links:'https://secret:pass@example.com'}));
assert.deepEqual(updatePageSettings(settings,'videos',{links:'https://example.com/video\n\n'}).pageContent.videos.links,['https://example.com/video']);
const draft={settings:{...settings,teams:[{id:'team-1',name:'Roma',eaClubId:'123'},{id:'team-2',name:'Bayern',eaClubId:'456'}]}};
const edited=editDraftTeam(draft,'team-1',{name:'UFL Roma',eaClubId:'789'});
assert.equal(edited.settings.teams[0].id,'team-1');assert.equal(edited.settings.teams[0].name,'UFL Roma');assert.equal(draft.settings.teams[0].name,'Roma');
assert.throws(()=>editDraftTeam(draft,'team-1',{name:'bayern'}));assert.throws(()=>editDraftTeam(draft,'team-1',{name:'Roma',eaClubId:'456'}));
assert.throws(()=>editDraftTeam({...draft,scheduleGenerated:true},'team-1',{name:'Roma'}));
assert.throws(()=>editDraftTeam(draft,'missing',{name:'Roma'}));
console.log('League page tests passed: empty publication, tab settings, link validation and safe team editing.');
