import assert from 'node:assert/strict';
import {createLeagueDraft,registerLeagueTeam,buildLeagueSchedule,fixtureCandidates,zonedTimestamp,validateScheduleSettings,validateTeamRules} from '../league-engine.js';
assert.equal(validateTeamRules({format:'6v6',size:8,maxTeamSize:12}).size,6);
assert.equal(validateTeamRules({format:'10v10',size:6,maxTeamSize:15}).size,10);
assert.equal(validateTeamRules({format:'Custom',size:8,maxTeamSize:13}).size,8);
assert.equal(validateTeamRules({format:'6v6',keepersEnabled:true}).size,6);
assert.equal(validateTeamRules({format:'6v6',keepersEnabled:false}).keepersEnabled,false);
assert.throws(()=>validateTeamRules({format:'10v10',maxTeamSize:9}));
assert.throws(()=>validateTeamRules({format:'6v6',maxTeamSize:6.5}));
assert.throws(()=>validateTeamRules({format:'Custom',size:12}));
assert.throws(()=>validateTeamRules({format:'6v6',keepersEnabled:'false'}));
assert.equal(validateTeamRules({format:'6v6'}).maxTeamSize,6);
const settings={season:'Season 2',league:'6v6',format:'6v6',size:6,startDate:'2026-10-15',weekday:4,time:'20:00',timeZone:'America/Chicago',spacingMinutes:30,teams:Array.from({length:8},(_,i)=>({id:`team-${i+1}`,name:`Team ${i+1}`,eaClubId:String(100+i)}))};
const schedule=buildLeagueSchedule(settings);
let empty=createLeagueDraft({...settings,teams:[]});
assert.equal(empty.settings.teams.length,0);assert.equal(empty.fixtures.length,0);assert.equal(empty.registrationOpen,true);
empty=registerLeagueTeam(empty,{name:'Roma'});
assert.equal(empty.settings.teams.length,1);assert.equal(empty.scheduleGenerated,false);
assert.throws(()=>registerLeagueTeam(empty,{name:' ROMA '}));
assert.throws(()=>registerLeagueTeam({...empty,registrationOpen:false},{name:'Toluca'}));
assert.equal(registerLeagueTeam(createLeagueDraft({...settings,league:'10v10',teams:[]}),{name:'Roma'}).settings.teams.length,1);
assert.throws(()=>buildLeagueSchedule(empty.settings));
empty=registerLeagueTeam(registerLeagueTeam(empty,{name:'Toluca',eaClubId:'123'}),{name:'Bayern'});
assert.throws(()=>registerLeagueTeam(empty,{name:'Other',eaClubId:'123'}));
assert.equal(buildLeagueSchedule(empty.settings).fixtures.length,6);
assert.equal(buildLeagueSchedule(empty.settings).registrationOpen,false);
assert.equal(createLeagueDraft(buildLeagueSchedule(empty.settings).settings).fixtures.length,0);
assert.equal(schedule.fixtures.length,56);assert.equal(schedule.nights.length,7);
const paused=buildLeagueSchedule({...settings,breaks:[{from:'2026-10-22',to:'2026-11-05',reason:'Cup / holiday break'}]});
assert.deepEqual(paused.nights.slice(0,3).map(night=>night.date),['2026-10-15','2026-11-12','2026-11-19']);
assert.equal(paused.fixtures.length,56);assert.equal(paused.skippedDates.length,3);
assert.deepEqual(paused.fixtures.map(game=>[game.home.id,game.away.id]),schedule.fixtures.map(game=>[game.home.id,game.away.id]));
assert.equal(new Date(paused.fixtures.find(game=>game.date==='2026-11-12').startsAt).toISOString(),'2026-11-13T02:00:00.000Z');
const fortnight=buildLeagueSchedule({...settings,repeatWeeks:2,breaks:[{from:'2026-10-29',to:'2026-10-29',reason:'Holiday'}]});
assert.deepEqual(fortnight.nights.slice(0,3).map(night=>night.date),['2026-10-15','2026-11-12','2026-11-26']);
assert.equal(fortnight.fixtures.length,56);
assert.throws(()=>validateScheduleSettings({...settings,repeatWeeks:0}));
assert.throws(()=>validateScheduleSettings({...settings,breaks:[{from:'2026-12-10',to:'2026-12-01',reason:'Break'}]}));
assert.throws(()=>zonedTimestamp('2026-02-30','20:00','America/Chicago'));
assert.equal(validateScheduleSettings({...settings,teams:[]}).teams.length,0);
for(const team of settings.teams){const games=schedule.fixtures.filter(game=>game.home.id===team.id||game.away.id===team.id);assert.equal(games.length,14);for(const night of schedule.nights){const tonight=night.fixtures.filter(game=>game.home.id===team.id||game.away.id===team.id);assert.equal(tonight.length,2);assert.notEqual(tonight[0].home.id===team.id?tonight[0].away.id:tonight[0].home.id,tonight[1].home.id===team.id?tonight[1].away.id:tonight[1].home.id);}for(const other of settings.teams.filter(other=>other.id!==team.id))assert.equal(games.filter(game=>game.home.id===other.id||game.away.id===other.id).length,2);}
assert.equal(new Date(zonedTimestamp('2026-10-29','20:00','America/Chicago')).toISOString(),'2026-10-30T01:00:00.000Z');
assert.equal(new Date(zonedTimestamp('2026-11-05','20:00','America/Chicago')).toISOString(),'2026-11-06T02:00:00.000Z');
assert.throws(()=>zonedTimestamp('2027-03-14','02:30','America/Chicago'));
assert.equal(buildLeagueSchedule({...settings,teams:settings.teams.slice(0,5)}).fixtures.length,20);
assert.throws(()=>buildLeagueSchedule({...settings,teams:settings.teams.slice(0,2)}));
const fixture=schedule.fixtures[0],game={matchId:'real',timestamp:fixture.startsAt/1000,clubs:{[fixture.home.eaClubId]:{},[fixture.away.eaClubId]:{}}};
assert.equal(fixtureCandidates(fixture,[game,game]).status,'review');
assert.equal(fixtureCandidates(fixture,[game,{...game,matchId:'other'}]).status,'ambiguous');
assert.equal(fixtureCandidates(fixture,[game],{acceptedMatchIds:['real']}).status,'waiting');
assert.equal(fixtureCandidates(fixture,[{...game,timestamp:game.timestamp+86400}]).status,'waiting');
assert.equal(fixtureCandidates(fixture,[{...game,clubs:{'999':{},[fixture.away.eaClubId]:{}}}]).status,'waiting');
console.log('PASS: double round-robin, two distinct opponents/night, odd-team byes, DST, duplicate games, unrelated games and ambiguous-result review.');
