import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {previewRegistrationApi as api} from '../functions/_lib/preview-registration.js';
import {sha256} from '../functions/_lib/auth.js';
import {updatePageSettings,removeDraftTeam} from '../league-page-model.js';
const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001_auth.sql',import.meta.url),'utf8'));
function adapter(){return {prepare(sql){return {args:[],bind(...args){this.args=args;return this;},async first(){return db.prepare(sql).get(...this.args)||null;},async all(){return {results:db.prepare(sql).all(...this.args)};},async run(){return {meta:{changes:db.prepare(sql).run(...this.args).changes}};}};},async batch(stmts){db.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}};}
const env={DB:adapter(),OWNER_DISCORD_ID:'owner'},origin='https://preview.example';
for(const [id,role] of [['owner','owner'],['admin','admin'],['manager','member'],['other','member'],['player','member'],['player2','member'],['player3','member']]){db.prepare('INSERT INTO users(discord_id,username,display_name,role) VALUES (?,?,?,?)').run(id,id,id,role);db.prepare("INSERT INTO sessions(id_hash,discord_id,expires_at) VALUES (?,?,datetime('now','+1 day'))").run(await sha256(id),id);}
const call=async(body,user='owner',query='',requestOrigin=origin)=>{const r=await api(new Request(origin+'/api/registration'+query,{method:body?'POST':'GET',headers:{origin:requestOrigin,cookie:'__Host-ufl_session='+user,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:r.status,...await r.json()};};
const settings={league:'6v6',season:'Season 2',format:'Custom',size:1,maxTeamSize:2,startDate:'2026-12-01',weekday:4,time:'20:00',timeZone:'America/Chicago',spacingMinutes:30,teams:[]};
assert.equal((await call({action:'create',settings,open:true},'manager')).status,403);
assert.equal((await call({action:'create',settings,open:true},'owner','', 'https://bad.example')).status,403);
assert.equal((await call({action:'create',settings,open:true},'missing')).status,401);
const invite=await call({action:'create',settings,open:true});assert.equal(invite.status,200);const token=new URL(invite.url).hash.slice(1);
assert.equal((await call(null,'manager','?token='+token)).kind,'manager');
assert.equal((await call({action:'team',token,name:'Roma',eaClubId:'123'},'manager')).status,200);
assert.equal((await call({action:'team',token,name:'Other',eaClubId:'123'},'other')).status,400);
assert.equal((await call(null,'manager','?board='+invite.boardId)).status,403);
let inbox=await call(null,'owner','?board='+invite.boardId);const teamId=inbox.teams[0].id;
assert.equal((await call({action:'playerLink',teamId},'manager')).status,409);
assert.equal((await call({action:'approve',teamId,boardId:invite.boardId},'manager')).status,403);
assert.equal((await call({action:'approve',teamId,boardId:invite.boardId})).approved,true);
assert.equal((await call({action:'playerLink',teamId},'other')).status,403);
const playerInvite=await call({action:'playerLink',teamId},'manager'),playerToken=new URL(playerInvite.url).hash.slice(1);
assert.equal((await call(null,'player','?token='+playerToken)).kind,'player');
assert.equal((await call({action:'player',token:playerToken,eaName:'Odez'},'player')).status,200);
assert.equal((await call({action:'player',token:playerToken,eaName:'Odez'},'player')).status,409);
assert.equal((await call({action:'player',token:playerToken,eaName:'Someone'},'player2')).status,200);
assert.equal((await call({action:'player',token:playerToken,eaName:'Full'},'player3')).status,400);
assert.equal((await call({action:'approvePlayer',boardId:invite.boardId,teamId,userId:'player'})).approved,true);
const board2=await call({action:'create',settings:{...settings,league:'10v10'},open:true});assert.equal((await call(null,'owner','?board='+board2.boardId)).teams.length,0);
await call({action:'update',settings,open:false,boardId:invite.boardId});assert.equal((await call({action:'team',token,name:'Late'},'other')).status,409);
const replacement=await call({action:'playerLink',teamId},'manager');assert.notEqual(replacement.url,playerInvite.url);assert.equal((await call(null,'player','?token='+playerToken)).status,404);
db.prepare('UPDATE preview_registration_boards SET expires=0 WHERE id=?').run(invite.boardId);assert.equal((await call(null,'player','?token='+token)).status,410);
assert.equal(db.prepare("SELECT COUNT(*) AS n FROM preview_player_requests WHERE status='approved'").get().n,1);
let streamSettings={teams:[{id:'team-1',name:'Roma'}]};streamSettings=updatePageSettings(streamSettings,'videos',{streams:[{teamId:'team-1',name:'Odez',url:'https://twitch.tv/odez'}]});assert.equal(streamSettings.pageContent.videos.streams[0].name,'Odez');
assert.throws(()=>updatePageSettings(streamSettings,'videos',{streams:[{teamId:'missing',name:'Odez',url:'https://twitch.tv/odez'}]}));
assert.throws(()=>updatePageSettings(streamSettings,'videos',{streams:[{teamId:'team-1',name:'Odez',url:'javascript:alert(1)'}]}));
assert.equal(removeDraftTeam({settings:streamSettings,scheduleGenerated:false},'team-1').settings.pageContent.videos.streams.length,0);
console.log('PASS: shared registration identity/authorization, isolation, approvals, link rotation/expiry, capacity, closures and team-linked stream validation.');
