import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {previewRegistrationApi as api} from '../functions/_lib/preview-registration.js';
import {sha256} from '../functions/_lib/auth.js';
import {updatePageSettings,removeDraftTeam} from '../league-page-model.js';
const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001_auth.sql',import.meta.url),'utf8'));
function adapter(){return {prepare(sql){return {args:[],bind(...args){this.args=args;return this;},async first(){return db.prepare(sql).get(...this.args)||null;},async all(){return {results:db.prepare(sql).all(...this.args)};},async run(){return {meta:{changes:db.prepare(sql).run(...this.args).changes}};}};},async batch(stmts){db.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}};}
const env={DB:adapter(),OWNER_DISCORD_ID:'owner'},origin='https://preview.example';
for(const [id,role] of [['owner','owner'],['admin','admin'],['manager','member'],['other','member'],['player','member'],['player2','member'],['player3','member']]){db.prepare('INSERT INTO users(discord_id,username,display_name,role) VALUES (?,?,?,?)').run(id,id,id,role);db.prepare("INSERT INTO sessions(id_hash,discord_id,expires_at) VALUES (?,?,datetime('now','+1 day'))").run(await sha256(id),id);}
const call=async(body,user='owner',query='',requestOrigin=origin)=>{const r=await api(new Request(origin+'/api/registration'+query,{method:body?'POST':'GET',headers:{origin:requestOrigin,cookie:'__Host-ufl_session='+user,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env);return {status:r.status,...await r.json()};};
const settings={league:'6v6',season:'Season 2',format:'Custom',size:1,maxTeamSize:2,startDate:'2026-12-01',weekday:4,time:'20:00',timeZone:'America/Chicago',spacingMinutes:30,teams:[]};
assert.equal((await call({action:'create',settings,open:true},'manager')).status,403);
assert.equal((await call({action:'create',settings,open:true},'owner','', 'https://bad.example')).status,403);
assert.equal((await call({action:'create',settings,open:true},'missing')).status,401);
const invite=await call({action:'create',settings,open:true});assert.equal(invite.status,200);const token=new URL(invite.url).hash.slice(1);
assert.equal((await call(null,'manager','?token='+token)).kind,'manager');
const teamInput={action:'team',token,name:'Roma',inGameName:'FC Roma EA',eaClubId:'123',platform:'ea',accountName:'ManagerEA'};
assert.equal((await call(teamInput,'manager')).status,403);
assert.equal((await call({action:'manager',boardId:invite.boardId,userId:'manager',active:true},'other')).status,403);
assert.equal((await call({action:'manager',boardId:invite.boardId,userId:'missing',active:true})).status,400);
for(const userId of ['manager','other'])assert.equal((await call({action:'manager',boardId:invite.boardId,userId,active:true})).status,200);
assert.equal((await call({...teamInput,inGameName:''},'manager')).status,400);
assert.equal((await call({...teamInput,platform:'password'},'manager')).status,400);
assert.equal((await call(teamInput,'manager')).status,200);
assert.equal((await call({...teamInput,name:'Other'},'other')).status,400);
assert.equal((await call(null,'manager','?board='+invite.boardId)).status,403);
let inbox=await call(null,'owner','?board='+invite.boardId);const teamId=inbox.teams[0].id;
assert.equal(inbox.teams[0].in_game_name,'FC Roma EA');
assert.equal(inbox.users.find(u=>u.id==='manager').manager,1);
assert.equal((await call({action:'updateTeam',token,name:'Roma New',inGameName:'Roma In Game',platform:'ea',accountName:'ManagerEA'},'manager')).status,200);
assert.equal((await call({action:'updateTeam',token,name:'Stolen',inGameName:'Bad',platform:'ea',accountName:'Other'},'other')).status,403);
assert.equal((await call({action:'playerLink',teamId},'manager')).status,409);
assert.equal((await call({action:'approve',teamId,boardId:invite.boardId},'manager')).status,403);
assert.equal((await call({action:'approve',teamId,boardId:invite.boardId})).approved,true);
assert.equal((await call({action:'playerLink',teamId},'other')).status,403);
const playerInvite=await call({action:'playerLink',teamId},'manager'),playerToken=new URL(playerInvite.url).hash.slice(1);
assert.equal((await call(null,'player','?token='+playerToken)).kind,'player');
const playerInput={action:'player',token:playerToken,platform:'psn',accountName:'Odez'};
assert.equal((await call({...playerInput,accountName:''},'player')).status,400);
assert.equal((await call(playerInput,'player')).status,200);
assert.equal((await call(playerInput,'player')).status,409);
assert.equal((await call({...playerInput,platform:'xbox',accountName:'Someone'},'player2')).status,200);
assert.equal((await call({...playerInput,accountName:'Full'},'player3')).status,400);
assert.equal((await call({action:'approvePlayer',boardId:invite.boardId,teamId,userId:'player'})).approved,true);
assert.equal((await call({action:'approvePlayer',boardId:invite.boardId,teamId,userId:'player'},'manager')).status,403);
assert.equal((await call(null,'manager','?token='+token)).roster[0].account_name,'Odez');
assert.equal((await call(null,'other','?token='+playerToken)).roster.length,0);
assert.equal((await call(null,'player','?token='+playerToken)).playerRequest.status,'approved');
// Different team, same league cannot claim the same Discord identity twice.
assert.equal((await call({...teamInput,name:'Other',eaClubId:'456'},'other')).status,200);
inbox=await call(null,'owner','?board='+invite.boardId);const otherTeam=inbox.teams.find(t=>t.manager_id==='other');
await call({action:'approve',boardId:invite.boardId,teamId:otherTeam.id});
const otherPlayerLink=await call({action:'playerLink',teamId:otherTeam.id},'other');
assert.equal((await call({...playerInput,token:new URL(otherPlayerLink.url).hash.slice(1)},'player')).status,409);
assert.equal((await call({action:'manager',boardId:invite.boardId,userId:'manager',active:false})).status,200);
assert.equal((await call({action:'playerLink',teamId},'manager')).status,403);
assert.equal((await call({action:'updateTeam',token,name:'No',inGameName:'No',platform:'ea',accountName:'No'},'manager')).status,403);
await call({action:'manager',boardId:invite.boardId,userId:'manager',active:true});
const board2=await call({action:'create',settings:{...settings,league:'10v10'},open:true});assert.equal((await call(null,'owner','?board='+board2.boardId)).teams.length,0);
const token2=new URL(board2.url).hash.slice(1);
assert.equal((await call({...teamInput,token:token2},'manager')).status,403); // Grants are league scoped.
await call({action:'manager',boardId:board2.boardId,userId:'manager',active:true});
assert.equal((await call({...teamInput,token:token2},'manager')).status,200);
const team2=(await call(null,'owner','?board='+board2.boardId)).teams[0];
await call({action:'approve',boardId:board2.boardId,teamId:team2.id});
const secondPlayer=await call({action:'playerLink',teamId:team2.id},'manager');
assert.equal((await call({...playerInput,token:new URL(secondPlayer.url).hash.slice(1)},'player')).status,200);
await call({action:'approvePlayer',boardId:board2.boardId,teamId:team2.id,userId:'player'});
assert.equal(db.prepare('SELECT COUNT(*) AS n FROM preview_roster_members WHERE user_id=?').get('player').n,2);
await call({action:'update',settings,open:false,boardId:invite.boardId});assert.equal((await call({action:'team',token,name:'Late'},'other')).status,409);
const replacement=await call({action:'playerLink',teamId},'manager');assert.notEqual(replacement.url,playerInvite.url);assert.equal((await call(null,'player','?token='+playerToken)).status,404);
db.prepare('UPDATE preview_registration_boards SET expires=0 WHERE id=?').run(invite.boardId);assert.equal((await call(null,'player','?token='+token)).status,410);
assert.equal(db.prepare("SELECT COUNT(*) AS n FROM preview_player_requests WHERE status='approved'").get().n,2);
// Personalized dashboards never expose another manager's teams or staff boards.
assert.equal((await call(null,'missing','?mine=1')).status,401);
let mine=await call(null,'player','?mine=1');assert.equal(mine.teams.length,0);assert.equal(mine.applications.length,2);assert.equal(mine.boards.length,0);assert.equal(mine.players.length,0);
assert.equal((await call({action:'profile',platform:'xbox',accountName:'Updated Player'},'player')).status,200);
assert.equal((await call(null,'player','?mine=1')).profile.accountName,'Updated Player');
assert.equal((await call({action:'dashboardTeam',teamId,name:'New Roma',inGameName:'Roma Game'},'other')).status,403);
assert.equal((await call({action:'dashboardTeam',teamId,name:'New Roma',inGameName:'Roma Game'},'manager')).status,200);
const targetSettings={...settings,season:'Season 3',startDate:'2027-03-01'};
const target=await call({action:'create',settings:targetSettings,open:true});
const rollover={action:'rollover',sourceBoardId:invite.boardId,boardId:target.boardId,teams:[{teamId,name:'Roma Returns',inGameName:'Roma FC'}],includeRoster:true,confirm:true};
assert.equal((await call(rollover,'manager')).status,403);
assert.equal((await call({...rollover,confirm:false})).status,400);
assert.equal((await call({...rollover,teams:[{teamId:team2.id}]})).status,400);
assert.equal((await call({...rollover,teams:[{teamId},{teamId}]})).status,400);
assert.equal((await call(null,'owner','?board='+target.boardId)).teams.length,0);
const rolled=await call(rollover);assert.equal(rolled.status,200);assert.equal(rolled.rolledOver,1);
const newBoard=await call(null,'owner','?board='+target.boardId);assert.equal(newBoard.teams.length,1);assert.equal(newBoard.teams[0].name,'Roma Returns');assert.equal(newBoard.teams[0].manager_id,'manager');assert.notEqual(newBoard.teams[0].id,teamId);assert.equal(newBoard.roster.length,1);
assert.equal((await call(null,'owner','?board='+invite.boardId)).teams.find(t=>t.id===teamId).name,'New Roma');
assert.equal((await call(rollover)).status,409);assert.equal((await call(null,'owner','?board='+target.boardId)).teams.length,1);
const managersOnly=await call({action:'create',settings:{...targetSettings,league:'Managers only'},open:true});
assert.equal((await call({...rollover,boardId:managersOnly.boardId,includeRoster:false})).status,200);
assert.equal((await call(null,'owner','?board='+managersOnly.boardId)).roster.length,0);
assert.equal((await call(null,'owner','?board='+managersOnly.boardId)).teams[0].manager_id,'manager');
const collision=await call({action:'create',settings:{...targetSettings,league:'Collision'},open:true});
const both=[{teamId,name:'Same',inGameName:'One'},{teamId:otherTeam.id,name:'Same',inGameName:'Two'}];
assert.equal((await call({...rollover,boardId:collision.boardId,teams:both,includeRoster:false})).status,409);
assert.equal((await call(null,'owner','?board='+collision.boardId)).teams.length,0); // Atomic rollback, including receipt.
assert.equal((await call({...rollover,boardId:collision.boardId,includeRoster:false})).status,200);
const existingTarget=await call({action:'create',settings:{...targetSettings,league:'Occupied'},open:true});
await call({action:'manager',boardId:existingTarget.boardId,userId:'other',active:true});
await call({...teamInput,token:new URL(existingTarget.url).hash.slice(1)},'other');
assert.equal((await call({...rollover,boardId:existingTarget.boardId})).status,409);
assert.equal((await call(null,'owner','?board='+existingTarget.boardId)).teams.length,1);
assert.equal((await call({action:'manager',boardId:target.boardId,userId:'manager',active:false})).status,200);
assert.equal((await call({action:'dashboardTeam',teamId:newBoard.teams[0].id,name:'No',inGameName:'No'},'manager')).status,403);
await call({action:'approvePlayer',boardId:invite.boardId,teamId,userId:'player2'});
const small=await call({action:'create',settings:{...targetSettings,league:'Small roster',maxTeamSize:1},open:true});
const tooLarge=await call({...rollover,boardId:small.boardId});assert.equal(tooLarge.status,409);assert.match(tooLarge.error,/roster exceeds/);
assert.equal((await call(null,'owner','?board='+small.boardId)).teams.length,0);
assert.equal((await call({...rollover,boardId:small.boardId,includeRoster:false})).status,200);
const badFormat=await call({action:'create',settings:{...targetSettings,league:'Wrong format',format:'6v6',size:6,maxTeamSize:12},open:true});
assert.equal((await call({...rollover,boardId:badFormat.boardId})).status,400);
let streamSettings={teams:[{id:'team-1',name:'Roma'}]};streamSettings=updatePageSettings(streamSettings,'videos',{streams:[{teamId:'team-1',name:'Odez',url:'https://twitch.tv/odez'}]});assert.equal(streamSettings.pageContent.videos.streams[0].name,'Odez');
assert.throws(()=>updatePageSettings(streamSettings,'videos',{streams:[{teamId:'missing',name:'Odez',url:'https://twitch.tv/odez'}]}));
assert.throws(()=>updatePageSettings(streamSettings,'videos',{streams:[{teamId:'team-1',name:'Odez',url:'javascript:alert(1)'}]}));
assert.equal(removeDraftTeam({settings:streamSettings,scheduleGenerated:false},'team-1').settings.pageContent.videos.streams.length,0);
console.log('PASS: registration, scoped dashboards/profile edits, manager authorization, concurrent leagues, selective atomic season rollover with optional rosters, history preservation, isolation and stream validation.');
